In [3]:
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from pandas import Series, DataFrame
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [2]:
ds = pd.read_csv("C:/BDSE26/df_0907.csv", sep=",")
ds

c:\Users\Student\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (25,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,sno,bike_lat,bike_lng,tot,time,date,Hr,weekday,weekday_num,holiday,...,Weather_lat,Weather_Dist,Generation,outlier,sarea,UVI,return_sec,rent_sec,rent_count,return_count
0,80,25.02751,121.495869,44,2017-01-04 12:00:00,2017-01-04,12,Wednesday,3,0,...,25.037658,2223.183703,1,True,萬華區,5,1729,15884,9,1
1,80,25.02751,121.495869,44,2017-01-07 05:00:00,2017-01-07,5,Saturday,6,1,...,25.037658,2223.183703,1,True,萬華區,0,1427,7507,2,1
2,80,25.02751,121.495869,44,2017-01-07 21:00:00,2017-01-07,21,Saturday,6,1,...,25.037658,2223.183703,1,True,萬華區,0,12290,16787,10,13
3,80,25.02751,121.495869,44,2017-01-09 07:00:00,2017-01-09,7,Monday,1,0,...,25.037658,2223.183703,1,True,萬華區,0,8997,8095,12,17
4,80,25.02751,121.495869,44,2017-01-14 12:00:00,2017-01-14,12,Saturday,6,1,...,25.037658,2223.183703,1,True,萬華區,1,5203,6130,7,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19212469,500112084,25.02976,121.564200,13,2022-04-30 17:00:00,2022-04-30,17,Saturday,6,1,...,25.037822,898.350579,2,True,信義區,0,2048,2914,3,2
19212470,500112084,25.02976,121.564200,13,2022-04-29 11:00:00,2022-04-29,11,Friday,5,0,...,25.037822,898.350579,2,True,信義區,6,741,645,2,1
19212471,500112084,25.02976,121.564200,13,2022-04-29 09:00:00,2022-04-29,9,Friday,5,0,...,25.037822,898.350579,2,True,信義區,4,0,2127,1,0
19212472,500112084,25.02976,121.564200,13,2022-04-29 18:00:00,2022-04-29,18,Friday,5,0,...,25.037822,898.350579,2,True,信義區,0,2402,3121,2,2
19212473,500112084,25.02976,121.564200,13,2022-04-29 16:00:00,2022-04-29,16,Friday,5,0,...,25.037822,898.350579,2,True,信義區,1,0,729,1,0

In [3]:
ds['sno'].astype('str')
ds['Hr'].astype('str')
ds['tot'].astype('str')
ds['weekday_num'].astype('str')

0           3
1           6
2           6
3           1
4           6
           ..
19212469    6
19212470    5
19212471    5
19212472    5
19212473    5
Name: weekday_num, Length: 19212474, dtype: object

In [4]:
import xgboost as xgb
from sklearn.model_selection import train_test_split

X_choice_reindex = ds.reindex(columns=[
    'sno', 'tot', 'Hr', 'weekday_num', 'holiday', 'school_off', 'Temperature',
    'RH', 'WS', 'rain', 'Precp', 'MRT_Out_ppl', 'MRT_Dist', 'School_Dist',
    'Weather_Dist', 'UVI', 'return_sec', 'rent_sec', 'return_count'
])
X_choice_reindex

,sno,tot,Hr,weekday_num,holiday,school_off,Temperature,RH,WS,rain,Precp,MRT_Out_ppl,MRT_Dist,School_Dist,Weather_Dist,UVI,return_sec,rent_sec,return_count
0,80,44,12,3,0,0,25.5,66.0,4.2,0,0.0,1324,934.143832,118.041403,2223.183703,5,1729,15884,1
1,80,44,5,6,1,1,21.5,87.0,1.2,0,0.0,0,934.143832,118.041403,2223.183703,0,1427,7507,1
2,80,44,21,6,1,1,21.4,79.0,0.3,0,0.0,1556,934.143832,118.041403,2223.183703,0,12290,16787,13
3,80,44,7,1,0,0,18.1,69.0,3.0,0,0.0,1238,934.143832,118.041403,2223.183703,0,8997,8095,17
4,80,44,12,6,1,1,13.6,85.0,4.5,0,0.0,1687,934.143832,118.041403,2223.183703,1,5203,6130,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19212469,500112084,13,17,6,1,1,20.5,87.0,1.0,0,0.0,988,336.624961,396.446516,898.350579,0,2048,2914,2
19212470,500112084,13,11,5,0,0,30.6,61.0,1.9,0,0.0,896,336.624961,396.446516,898.350579,6,741,645,1
19212471,500112084,13,9,5,0,0,28.4,71.0,0.0,0,0.0,2736,336.624961,396.446516,898.350579,4,0,2127,0
19212472,500112084,13,18,5,0,0,21.2,87.0,1.9,0,0.0,1355,336.624961,396.446516,898.350579,0,2402,3121,2
19212473,500112084,13,16,5,0,0,22.6,86.0,2.1,0,0.0,713,336.624961,396.446516,898.350579,1,0,729,0

In [5]:
df = X_choice_reindex.values
X = df[:, 0:18]
y = df[:, 18]
y = y.astype('int64')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [6]:
import xgboost as xgb
import pickle
#Scikit-learn 接口回歸模型
# 建立xgbrModel模型
xgbrModel = xgb.XGBRegressor(n_estimators=400,
                             learning_rate=0.1,
                             max_depth=7,
                             min_child_weight=3,
                             subsample=0.7,
                             colsample_bytree=0.9,
                             gamma=0.1,
                             reg_alpha=0.1,
                             reg_lambda=0.05,
                             silent=True,
                             tree_method='gpu_hist',
                             n_jobs=7)
# 使用訓練資料訓練模型
xgbrModel.fit(X_train, y_train)
kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
results = cross_val_score(xgbrModel, X, y, cv=kfold)

pickle.dump(xgbrModel, open("XGBOOST回歸return.pkl", "wb"))

[16:23:14] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

c:\Users\Student\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(

[16:25:33] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:27:55] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:30:19] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:32:42] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:35:04] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:37:25] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:39:45] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:42:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:44:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[16:46:47] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

In [7]:
from sklearn import metrics
# 使用test資料預測
predicted = xgbrModel.predict(X_test)
#predicted = xgbrModel.predict(X_test)
print('R2 score: ', xgbrModel.score(X_test, y_test))
mse = metrics.mean_squared_error(y_test, predicted)
print('MSE score: ', mse)

R2 score:  0.9088556569464796
MSE score:  8.493954589177426

In [8]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error, mean_absolute_percentage_error
#定義回歸模型評估誤差指標
print('回歸模型評估指標結果:')
print('均方誤差【MSE】:', mean_squared_error(y_test, predicted))
print('均方根誤差【RMSE】:', np.sqrt(mean_squared_error(y_test, predicted)))
print('平均絕對誤差【MAE】:', mean_absolute_error(y_test, predicted))
print('絕對誤差中位數【MedianAE】:', median_absolute_error(y_test, predicted))
print('平均絕對百分比誤差【MAPE】:', np.median(np.abs((predicted - y_test) / y_test)))

回歸模型評估指標結果:
均方誤差【MSE】: 8.493954589177426
均方根誤差【RMSE】: 2.9144389836085822
平均絕對誤差【MAE】: 1.6621672033463881
絕對誤差中位數【MedianAE】: 0.8649076223373413
平均絕對百分比誤差【MAPE】: 0.270483477362271

C:\Users\Student\AppData\Local\Temp\ipykernel_18428\1100501718.py:8: RuntimeWarning: divide by zero encountered in true_divide
  print('平均絕對百分比誤差【MAPE】:', np.median(np.abs((predicted - y_test) / y_test)))

In [9]:
xgbrModel.fit(X, y)
predicted = xgbrModel.predict(X)

[16:49:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576:
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

In [10]:
ds['return_predicted'] = predicted
ds

,sno,bike_lat,bike_lng,tot,time,date,Hr,weekday,weekday_num,holiday,...,Weather_Dist,Generation,outlier,sarea,UVI,return_sec,rent_sec,rent_count,return_count,return_predicted
0,80,25.02751,121.495869,44,2017-01-04 12:00:00,2017-01-04,12,Wednesday,3,0,...,2223.183703,1,True,萬華區,5,1729,15884,9,1,4.263834
1,80,25.02751,121.495869,44,2017-01-07 05:00:00,2017-01-07,5,Saturday,6,1,...,2223.183703,1,True,萬華區,0,1427,7507,2,1,1.798232
2,80,25.02751,121.495869,44,2017-01-07 21:00:00,2017-01-07,21,Saturday,6,1,...,2223.183703,1,True,萬華區,0,12290,16787,10,13,12.175045
3,80,25.02751,121.495869,44,2017-01-09 07:00:00,2017-01-09,7,Monday,1,0,...,2223.183703,1,True,萬華區,0,8997,8095,12,17,15.194024
4,80,25.02751,121.495869,44,2017-01-14 12:00:00,2017-01-14,12,Saturday,6,1,...,2223.183703,1,True,萬華區,1,5203,6130,7,8,6.352099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19212469,500112084,25.02976,121.564200,13,2022-04-30 17:00:00,2022-04-30,17,Saturday,6,1,...,898.350579,2,True,信義區,0,2048,2914,3,2,2.918898
19212470,500112084,25.02976,121.564200,13,2022-04-29 11:00:00,2022-04-29,11,Friday,5,0,...,898.350579,2,True,信義區,6,741,645,2,1,1.583600
19212471,500112084,25.02976,121.564200,13,2022-04-29 09:00:00,2022-04-29,9,Friday,5,0,...,898.350579,2,True,信義區,4,0,2127,1,0,0.398041
19212472,500112084,25.02976,121.564200,13,2022-04-29 18:00:00,2022-04-29,18,Friday,5,0,...,898.350579,2,True,信義區,0,2402,3121,2,2,3.461994
19212473,500112084,25.02976,121.564200,13,2022-04-29 16:00:00,2022-04-29,16,Friday,5,0,...,898.350579,2,True,信義區,1,0,729,1,0,0.105106

In [11]:
ds.to_csv("return_predicted.csv", index=None)

In [4]:
data_return = pd.read_csv("C:/BDSE26/return_predicted.csv",sep = ",")
data_return

c:\Users\Student\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (25,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,sno,bike_lat,bike_lng,tot,time,date,Hr,weekday,weekday_num,holiday,...,Weather_Dist,Generation,outlier,sarea,UVI,return_sec,rent_sec,rent_count,return_count,return_predicted
0,80,25.02751,121.495869,44,2017-01-04 12:00:00,2017-01-04,12,Wednesday,3,0,...,2223.183703,1,True,萬華區,5,1729,15884,9,1,4.263834
1,80,25.02751,121.495869,44,2017-01-07 05:00:00,2017-01-07,5,Saturday,6,1,...,2223.183703,1,True,萬華區,0,1427,7507,2,1,1.798232
2,80,25.02751,121.495869,44,2017-01-07 21:00:00,2017-01-07,21,Saturday,6,1,...,2223.183703,1,True,萬華區,0,12290,16787,10,13,12.175045
3,80,25.02751,121.495869,44,2017-01-09 07:00:00,2017-01-09,7,Monday,1,0,...,2223.183703,1,True,萬華區,0,8997,8095,12,17,15.194024
4,80,25.02751,121.495869,44,2017-01-14 12:00:00,2017-01-14,12,Saturday,6,1,...,2223.183703,1,True,萬華區,1,5203,6130,7,8,6.352099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19212469,500112084,25.02976,121.564200,13,2022-04-30 17:00:00,2022-04-30,17,Saturday,6,1,...,898.350579,2,True,信義區,0,2048,2914,3,2,2.918898
19212470,500112084,25.02976,121.564200,13,2022-04-29 11:00:00,2022-04-29,11,Friday,5,0,...,898.350579,2,True,信義區,6,741,645,2,1,1.583600
19212471,500112084,25.02976,121.564200,13,2022-04-29 09:00:00,2022-04-29,9,Friday,5,0,...,898.350579,2,True,信義區,4,0,2127,1,0,0.398041
19212472,500112084,25.02976,121.564200,13,2022-04-29 18:00:00,2022-04-29,18,Friday,5,0,...,898.350579,2,True,信義區,0,2402,3121,2,2,3.461994
19212473,500112084,25.02976,121.564200,13,2022-04-29 16:00:00,2022-04-29,16,Friday,5,0,...,898.350579,2,True,信義區,1,0,729,1,0,0.105106

In [5]:
data_rent = pd.read_csv("C:/BDSE26/rent_predicted.csv",sep = ",")
data_rent

c:\Users\Student\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (25,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,sno,bike_lat,bike_lng,tot,time,date,Hr,weekday,weekday_num,holiday,...,Weather_Dist,Generation,outlier,sarea,UVI,return_sec,rent_sec,rent_count,return_count,rent_predicted
0,80,25.02751,121.495869,44,2017-01-04 12:00:00,2017-01-04,12,Wednesday,3,0,...,2223.183703,1,True,萬華區,5,1729,15884,9,1,9.505536
1,80,25.02751,121.495869,44,2017-01-07 05:00:00,2017-01-07,5,Saturday,6,1,...,2223.183703,1,True,萬華區,0,1427,7507,2,1,3.330941
2,80,25.02751,121.495869,44,2017-01-07 21:00:00,2017-01-07,21,Saturday,6,1,...,2223.183703,1,True,萬華區,0,12290,16787,10,13,12.866616
3,80,25.02751,121.495869,44,2017-01-09 07:00:00,2017-01-09,7,Monday,1,0,...,2223.183703,1,True,萬華區,0,8997,8095,12,17,10.097020
4,80,25.02751,121.495869,44,2017-01-14 12:00:00,2017-01-14,12,Saturday,6,1,...,2223.183703,1,True,萬華區,1,5203,6130,7,8,6.644071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19212469,500112084,25.02976,121.564200,13,2022-04-30 17:00:00,2022-04-30,17,Saturday,6,1,...,898.350579,2,True,信義區,0,2048,2914,3,2,3.470536
19212470,500112084,25.02976,121.564200,13,2022-04-29 11:00:00,2022-04-29,11,Friday,5,0,...,898.350579,2,True,信義區,6,741,645,2,1,1.593765
19212471,500112084,25.02976,121.564200,13,2022-04-29 09:00:00,2022-04-29,9,Friday,5,0,...,898.350579,2,True,信義區,4,0,2127,1,0,3.594104
19212472,500112084,25.02976,121.564200,13,2022-04-29 18:00:00,2022-04-29,18,Friday,5,0,...,898.350579,2,True,信義區,0,2402,3121,2,2,4.238611
19212473,500112084,25.02976,121.564200,13,2022-04-29 16:00:00,2022-04-29,16,Friday,5,0,...,898.350579,2,True,信義區,1,0,729,1,0,1.715841

In [6]:
data_return['rent_predicted']=data_rent['rent_predicted']
data_return

,sno,bike_lat,bike_lng,tot,time,date,Hr,weekday,weekday_num,holiday,...,Generation,outlier,sarea,UVI,return_sec,rent_sec,rent_count,return_count,return_predicted,rent_predicted
0,80,25.02751,121.495869,44,2017-01-04 12:00:00,2017-01-04,12,Wednesday,3,0,...,1,True,萬華區,5,1729,15884,9,1,4.263834,9.505536
1,80,25.02751,121.495869,44,2017-01-07 05:00:00,2017-01-07,5,Saturday,6,1,...,1,True,萬華區,0,1427,7507,2,1,1.798232,3.330941
2,80,25.02751,121.495869,44,2017-01-07 21:00:00,2017-01-07,21,Saturday,6,1,...,1,True,萬華區,0,12290,16787,10,13,12.175045,12.866616
3,80,25.02751,121.495869,44,2017-01-09 07:00:00,2017-01-09,7,Monday,1,0,...,1,True,萬華區,0,8997,8095,12,17,15.194024,10.097020
4,80,25.02751,121.495869,44,2017-01-14 12:00:00,2017-01-14,12,Saturday,6,1,...,1,True,萬華區,1,5203,6130,7,8,6.352099,6.644071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19212469,500112084,25.02976,121.564200,13,2022-04-30 17:00:00,2022-04-30,17,Saturday,6,1,...,2,True,信義區,0,2048,2914,3,2,2.918898,3.470536
19212470,500112084,25.02976,121.564200,13,2022-04-29 11:00:00,2022-04-29,11,Friday,5,0,...,2,True,信義區,6,741,645,2,1,1.583600,1.593765
19212471,500112084,25.02976,121.564200,13,2022-04-29 09:00:00,2022-04-29,9,Friday,5,0,...,2,True,信義區,4,0,2127,1,0,0.398041,3.594104
19212472,500112084,25.02976,121.564200,13,2022-04-29 18:00:00,2022-04-29,18,Friday,5,0,...,2,True,信義區,0,2402,3121,2,2,3.461994,4.238611
19212473,500112084,25.02976,121.564200,13,2022-04-29 16:00:00,2022-04-29,16,Friday,5,0,...,2,True,信義區,1,0,729,1,0,0.105106,1.715841

In [8]:
data_return.to_csv("All_predicted.csv", index=False)