In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from pandas import Series, DataFrame

In [2]:
Bike = pd.read_csv("C:/BDSE26/df_0907.csv",sep = ",")
Bike

c:\Users\Student\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (25,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,sno,bike_lat,bike_lng,tot,time,date,Hr,weekday,weekday_num,holiday,...,Weather_lat,Weather_Dist,Generation,outlier,sarea,UVI,return_sec,rent_sec,rent_count,return_count
0,80,25.02751,121.495869,44,2017-01-04 12:00:00,2017-01-04,12,Wednesday,3,0,...,25.037658,2223.183703,1,True,萬華區,5,1729,15884,9,1
1,80,25.02751,121.495869,44,2017-01-07 05:00:00,2017-01-07,5,Saturday,6,1,...,25.037658,2223.183703,1,True,萬華區,0,1427,7507,2,1
2,80,25.02751,121.495869,44,2017-01-07 21:00:00,2017-01-07,21,Saturday,6,1,...,25.037658,2223.183703,1,True,萬華區,0,12290,16787,10,13
3,80,25.02751,121.495869,44,2017-01-09 07:00:00,2017-01-09,7,Monday,1,0,...,25.037658,2223.183703,1,True,萬華區,0,8997,8095,12,17
4,80,25.02751,121.495869,44,2017-01-14 12:00:00,2017-01-14,12,Saturday,6,1,...,25.037658,2223.183703,1,True,萬華區,1,5203,6130,7,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19212469,500112084,25.02976,121.564200,13,2022-04-30 17:00:00,2022-04-30,17,Saturday,6,1,...,25.037822,898.350579,2,True,信義區,0,2048,2914,3,2
19212470,500112084,25.02976,121.564200,13,2022-04-29 11:00:00,2022-04-29,11,Friday,5,0,...,25.037822,898.350579,2,True,信義區,6,741,645,2,1
19212471,500112084,25.02976,121.564200,13,2022-04-29 09:00:00,2022-04-29,9,Friday,5,0,...,25.037822,898.350579,2,True,信義區,4,0,2127,1,0
19212472,500112084,25.02976,121.564200,13,2022-04-29 18:00:00,2022-04-29,18,Friday,5,0,...,25.037822,898.350579,2,True,信義區,0,2402,3121,2,2
19212473,500112084,25.02976,121.564200,13,2022-04-29 16:00:00,2022-04-29,16,Friday,5,0,...,25.037822,898.350579,2,True,信義區,1,0,729,1,0

In [3]:
Bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19212474 entries, 0 to 19212473
Data columns (total 45 columns):
 #   Column         Dtype
---  ------         -----
 0   sno            int64
 1   bike_lat       float64
 2   bike_lng       float64
 3   tot            int64
 4   time           object
 5   date           object
 6   Hr             int64
 7   weekday        object
 8   weekday_num    int64
 9   holiday        int64
 10  school_off     int64
 11  Temperature    float64
 12  RH             float64
 13  WS             float64
 14  rain           int64
 15  Precp          float64
 16  MRT_Out_ppl    int64
 17  ar             object
 18  MRT_Dist       float64
 19  School_Dist    float64
 20  sna            object
 21  station        object
 22  MRT_Station    object
 23  MRT_No         object
 24  MRT_Exit_Name  object
 25  Exit_No        object
 26  MRT_lng        float64
 27  MRT_lat        float64
 28  School         object
 29  School_lat     float64
 30  School_lng     float64
 31  StationID      object
 32  WeatherSiteID  object
 33  WeatherSite    object
 34  Weather_lng    float64
 35  Weather_lat    float64
 36  Weather_Dist   float64
 37  Generation     int64
 38  outlier        bool
 39  sarea          object
 40  UVI            int64
 41  return_sec     int64
 42  rent_sec       int64
 43  rent_count     int64
 44  return_count   int64
dtypes: bool(1), float64(15), int64(14), object(15)
memory usage: 6.3+ GB

In [4]:
Bike['sno'].astype('str')
Bike['tot'].astype('str')
Bike['Hr'].astype('str')
Bike['weekday_num'].astype('str')
Bike['MRT_Out_ppl'].astype('str')

0           1324
1              0
2           1556
3           1238
4           1687
            ...
19212469     988
19212470     896
19212471    2736
19212472    1355
19212473     713
Name: MRT_Out_ppl, Length: 19212474, dtype: object

In [5]:
ds= DataFrame(Bike)
X_choice = ds.loc[:, ['sno',  'tot', 'Hr', 'weekday_num', 'holiday', 'school_off', 'Temperature', 'RH', 'WS',
       'rain', 'Precp', 'MRT_Out_ppl', 'MRT_Dist', 'School_Dist',  'Weather_Dist', 'Generation', 'UVI', 'return_sec','rent_sec', 'rent_count']]
ds = X_choice.values
X = ds[:, 0:19]
y = ds[:, 19]
y = y.astype('int64')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [6]:
model = linear_model.Lasso(alpha=0.1)
model.fit(X_train, y_train)
diabetes_y_pred = model.predict(X_test)

In [7]:
# The coefficients
print('Coefficients: {}\n'.format(model.coef_))
# The mean squared error
print('number of model coef: {}'.format(np.sum(model.coef_ != 0)))

Coefficients: [-4.76787392e-09  3.64997279e-02  4.93470098e-02 -8.48134786e-02
 -1.36010276e-01 -6.09537191e-01  3.79024181e-02 -3.25014165e-02
 -7.04436991e-02 -2.77965559e-03 -1.20040490e-01  1.30524945e-03
 -2.75966701e-03 -1.60970179e-03  4.33836879e-05  0.00000000e+00
 -1.27775195e-01  1.44595936e-04  2.20114039e-04]

number of model coef: 18